/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package reportmaker;

/**
 *
 * @author WIN11PC
 */

import java.util.List;

public class BulkReportGenerator {
    
    private PDFExportService pdfService = new PDFExportService();

    // 1. Generate FULL Student List PDF
    public String generateBulkPdf(List<Student> students) {
        StringBuilder sb = new StringBuilder();
        
        sb.append("OFFICIAL BULK STUDENT SUMMARY\n");
        sb.append("Generated by: Course Administrator\n");
        sb.append("======================================================================\n");
        sb.append(String.format("%-10s %-20s %-30s %-8s\n", "ID", "Name", "Program", "CGPA"));
        sb.append("======================================================================\n");

        for (Student s : students) {
            String name = (s.getName().length() > 18) ? s.getName().substring(0, 15) + "..." : s.getName();
            String prog = (s.getProgram().length() > 28) ? s.getProgram().substring(0, 25) + "..." : s.getProgram();
            
            sb.append(String.format("%-10s %-20s %-30s %-8.2f\n", 
                s.getId(), name, prog, s.getCGPA()));
        }
        sb.append("----------------------------------------------------------------------\n");
        sb.append("Total Students: " + students.size() + "\n");

        // Create PDF
        String filename = "Bulk_Student_List.pdf";
        pdfService.createPdf(filename, sb.toString());
        
        return "Success! Saved to: " + filename;
    }

    // 2. Generate AT-RISK Student Report PDF
    public String generateAtRiskPdf(List<Student> students) {
        StringBuilder sb = new StringBuilder();
        
        sb.append("CONFIDENTIAL: AT-RISK STUDENT REPORT\n");
        sb.append("Criteria: CGPA < 2.0 OR Failed Courses > 3\n");
        sb.append("======================================================================\n");
        sb.append(String.format("%-10s %-20s %-8s %-8s %-15s\n", "ID", "Name", "CGPA", "Fails", "Reason"));
        sb.append("======================================================================\n");

        int count = 0;
        for (Student s : students) {
            if (s.getCGPA() < 2.0 || s.getFailedCourseCount() > 3) {
                String reason = (s.getCGPA() < 2.0) ? "Low CGPA" : "Many Fails";
                if (s.getCGPA() < 2.0 && s.getFailedCourseCount() > 3) reason = "BOTH";
                
                String name = (s.getName().length() > 18) ? s.getName().substring(0, 15) + "..." : s.getName();
                
                sb.append(String.format("%-10s %-20s %-8.2f %-8d %-15s\n", 
                    s.getId(), name, s.getCGPA(), s.getFailedCourseCount(), reason));
                count++;
            }
        }
        
        if (count == 0) {
            sb.append("\n   Good News: No students are currently at-risk.\n");
        }
        
        sb.append("----------------------------------------------------------------------\n");
        sb.append("Total At-Risk Students: " + count + "\n");

        // Create PDF
        String filename = "At_Risk_Report.pdf";
        pdfService.createPdf(filename, sb.toString());
        
        return "Success! Saved to: " + filename;
    }
}