/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package reportmaker;

import java.util.List;

/**
 *
 * @author WIN11PC
 */



public class StudentReportGenerator {
    
    private PDFExportService pdfService = new PDFExportService();
    private EmailService emailService = new EmailService(); // Add Email Service

    
    public String generateReportText(Student s, int sem) {
        StringBuilder sb = new StringBuilder();
        
        String title = (sem > 0) ? "SEMESTER " + sem + " REPORT" : "FULL ACADEMIC TRANSCRIPT";
        
        sb.append("OFFICIAL ACADEMIC REPORT\n");
        sb.append("=============================================================\n");
        sb.append(" Student Name : " + s.getName() + "\n");
        sb.append(" Student ID   : " + s.getId() + "\n");
        sb.append(" Program      : " + s.getProgram() + "\n");
        sb.append(" Report Type  : " + title + "\n");
        sb.append("=============================================================\n");
        sb.append(String.format("%-10s %-30s %-5s %-5s\n", "Code", "Course Title", "Grd", "Pnt"));
        sb.append("-------------------------------------------------------------\n");

        List<Course> list = (sem > 0) ? s.getCoursesBySemester(sem) : s.getCourses();
        double totalPoints = 0;
        double totalCredits = 0;

        if (list.isEmpty()) {
            sb.append("       [No records found for this selection]\n");
        } else {
            for (Course c : list) {
                String shortTitle = c.getTitle();
                if(shortTitle.length() > 28) shortTitle = shortTitle.substring(0, 25) + "...";
                
                sb.append(String.format("%-10s %-30s %-5s %-5.1f\n", 
                    c.getCode(), shortTitle, c.getGrade(), c.getPoint()));
                
                totalPoints += (c.getPoint() * c.getCredit());
                totalCredits += c.getCredit();
            }
        }
        
        double gpa = (totalCredits == 0) ? 0.0 : (totalPoints / totalCredits);
        
        sb.append("-------------------------------------------------------------\n");
        if (sem > 0) {
            sb.append(String.format(" Semester GPA:         %.2f\n", gpa));
        } else {
            sb.append(String.format(" Cumulative GPA (CGPA): %.2f\n", s.getCGPA()));
        }
        sb.append("=============================================================\n");
        sb.append(" Generated by: Academic Officer System\n");
        
        return sb.toString();
    }

    
    public String saveToPdf(String content, String studentId) {
        String filename = "Transcript_" + studentId + ".pdf";
        pdfService.createPdf(filename, content);
        return filename;
    }

    
    public void sendReportEmail(Student s, String content) {
        // Sends the report text to the student's email
        emailService.sendNotification(s.getEmail(), content);
    }
}