package Assignment;

import java.awt.Color;
import java.util.logging.Logger;
import javax.swing.*;


public class LoginFrame extends javax.swing.JFrame {
    
    private static final Logger logger = Logger.getLogger(LoginFrame.class.getName());
    
    private Authentication authentication;
    private AccessControl accessControl;
    private UserManager userManager;
    private UserFileRepository userRepo;
    private PasswordResetService passwordResetService;
    private LoginService loginService;
    private UserManagementService userManagementService;
    
    private static final String ROLE_COURSE_ADMIN = "Course Adminstractor";
    private static final String ROLE_ACADEMIC_OFFICER = "Academic Officer";
    private static final String ROLE_ADMIN = "ADMIN";

    public LoginFrame() {
        initComponents();
        initServices();
        customInit();
    }
    
    private void customInit() {
        getRootPane().setDefaultButton(btnLogin);
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Course Recovery System - Login");
    }
    
    private void initServices() {
        userRepo = new UserFileRepository("users.txt");    // calls UserFileRepository constructor
    java.util.Map<String, User> users = userRepo.loadUsers();   // calls UserFileRepository.loadUsers()

    userManager = new UserManager(users, userRepo);   // calls UserManager constructor

    if (users.isEmpty()) {
        User admin = new User(   // calls User constructor
            0, 
            "admin",
            "Admin User",
            "admin123",
            "admin@example.com",
            ROLE_ADMIN
        );
        userManager.addUser(admin);   // calls UserManager.addUser()
        users = userManager.getAllUsers();   // calls UserManager.getAllUsers()
        }

        authentication = new Authentication(users);   // calls Authentication constructor

        accessControl = new AccessControl();    // calls AccessControl constructor
        setupRolePermissions();
        
        passwordResetService = new PasswordResetService();   // calls PasswordResetService constructor

        loginService = new LoginService(authentication, accessControl, userManager, passwordResetService, userRepo);
        
        userManagementService = new UserManagementService(userManager, accessControl, authentication);
    }
    
    private void setupRolePermissions() {
        accessControl.addPermissionToRole(ROLE_COURSE_ADMIN, "LOGIN");
        accessControl.addPermissionToRole(ROLE_COURSE_ADMIN, "MANAGE_USERS");
        
        accessControl.addPermissionToRole(ROLE_ACADEMIC_OFFICER, "LOGIN");
        accessControl.addPermissionToRole(ROLE_ACADEMIC_OFFICER, "MANAGE_USERS");
        
        accessControl.addPermissionToRole(ROLE_ADMIN, "LOGIN");
        accessControl.addPermissionToRole(ROLE_ADMIN, "MANAGE_USERS");
    }

    public boolean completePasswordReset(String token, String newPassword) {
        return loginService.completePasswordReset(token, newPassword);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnResetPassword = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Login Page");
        setForeground(java.awt.Color.white);

        jLabel1.setText("Username：");

        jLabel2.setText("Password：");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblMessage.setText(" ");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("User Login Pages");

        btnResetPassword.setText("Reset Password");
        btnResetPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 42, Short.MAX_VALUE)
                        .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUsername)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnResetPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(btnResetPassword))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String username = txtUsername.getText().trim();
        String password = new String(txtPassword.getPassword());

        // Second click: If already logged in, enter main menu
        if (username.isEmpty() || password.isEmpty()) {
            showError("Please enter username and password.");
            return;
        }
        // First click: Perform login validation
        LoginService.LoginResult result = loginService.login(username, password);

        if (result.success) {
            showSuccess(result.message);
            
            MainMenuFrame mainMenu = new MainMenuFrame(
                authentication, 
                accessControl, 
                userManager, 
                result.user,
                userManagementService
            );
            mainMenu.setVisible(true);
            
            this.dispose();
            
        } else {
            showError(result.message);
            txtPassword.setText("");
            txtPassword.requestFocus();
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnResetPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetPasswordActionPerformed
        String usernameOrEmail = txtUsername.getText().trim();

        if (usernameOrEmail.isEmpty()) {
            showError("Please enter your username or email first.");
            return;
        }

        LoginService.ResetRequestResult result = loginService.requestPasswordReset(usernameOrEmail);

        if (result.success) {
            showSuccess(result.message);
        } else {
            showError(result.message);
        }
    }//GEN-LAST:event_btnResetPasswordActionPerformed

    private void showError(String message) {
        lblMessage.setForeground(Color.RED);
        lblMessage.setText(message);
    }
    
    private void showSuccess(String message) {
        lblMessage.setForeground(new Color(0, 128, 0));
        lblMessage.setText(message);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new LoginFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnResetPassword;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
