/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Assignment;

import java.awt.Color;
import javax.swing.*;
/**
 *
 * @author ASUS
 */
public class MainMenuFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainMenuFrame.class.getName());
    private Authentication authentication;
    private AccessControl accessControl;
    private UserManager userManager;
    private User currentUser;
    private UserManagementService userManagementService;
    /**
     * Creates new form MainMenuFrame
     */
    public MainMenuFrame() {
        initComponents();
    }
    
    public MainMenuFrame(Authentication authentication, 
                         AccessControl accessControl,
                         UserManager userManager, 
                         User currentUser,
                         UserManagementService userManagementService) {
        this.authentication = authentication;
        this.accessControl = accessControl;
        this.userManager = userManager;
        this.currentUser = currentUser;
        this.userManagementService = userManagementService;

        initComponents();
        customInit();
    }
    
    private void customInit() {
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Course Recovery System - Main Menu");
        
        lblWelcome.setText("Welcome, " + currentUser.getFullName() + "!");
        
        setupPermissions();
    }

     private void setupPermissions() {
        boolean canManageUsers = accessControl.hasPermission(currentUser, "MANAGE_USERS");
        
        btnCourseRecovery.setEnabled(true);
        btnEligibilityCheck.setEnabled(true);
        btnAcademicReport.setEnabled(true);
        
        btnUserManagement.setEnabled(canManageUsers);
        
        if (!canManageUsers) {
            btnUserManagement.setToolTipText("You do not have permission to access this feature");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        btnUserManagement = new javax.swing.JButton();
        btnCourseRecovery = new javax.swing.JButton();
        btnEligibilityCheck = new javax.swing.JButton();
        btnAcademicReport = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblWelcome.setText("Welcome!");

        btnUserManagement.setText("User Management");
        btnUserManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserManagementActionPerformed(evt);
            }
        });

        btnCourseRecovery.setText("Course Recovery Plan");
        btnCourseRecovery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseRecoveryActionPerformed(evt);
            }
        });

        btnEligibilityCheck.setText("Eligibility Check & Enrolment");

        btnAcademicReport.setText("Academic Performance Report");

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnUserManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCourseRecovery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEligibilityCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAcademicReport, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)))))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUserManagement)
                .addGap(18, 18, 18)
                .addComponent(btnCourseRecovery)
                .addGap(18, 18, 18)
                .addComponent(btnEligibilityCheck)
                .addGap(18, 18, 18)
                .addComponent(btnAcademicReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserManagementActionPerformed
        if (!accessControl.hasPermission(currentUser, "MANAGE_USERS")) {
            JOptionPane.showMessageDialog(this,
                "You do not have permission to manage user accounts.",
                "Access Denied",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        UserManagementFrame umf = new UserManagementFrame(
            authentication, accessControl, userManager, currentUser, userManagementService
        );
        umf.setVisible(true);
    }//GEN-LAST:event_btnUserManagementActionPerformed

    private void btnCourseRecoveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseRecoveryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCourseRecoveryActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
         userManagementService.logout(currentUser);
        
        LoginFrame loginFrame = new LoginFrame();
        loginFrame.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName())
                .log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            // new MainMenuFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcademicReport;
    private javax.swing.JButton btnCourseRecovery;
    private javax.swing.JButton btnEligibilityCheck;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnUserManagement;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
